---
# tasks file for lb-tier
#
- name: Install Packages
  yum: pkg={{item}} state=latest
  with_items:
    - httpd 
    - haproxy 
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
- name: enable HAProxy
  service:
    name: haproxy
    state: started

